version: "3"

services:
  api:
    image: birthdayweb
    build:
      context: .
      dockerfile: BirthdayWeb/Dockerfile
    ports:
      - "5279:80"
    depends_on:
      - database
    networks:
      - default
  database:
    image: mysql
    container_name: mysqldatabase
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=pw
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default:
    driver: bridge
